config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products

  root to: 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'

  match '/products', to: 'static_pages#products', via: 'get'

  match '/sustainability', to: 'static_pages#sustainability', via: 'get'

  match '/services', to: 'static_pages#services', via: 'get'

  resource :contacts, only: [:new, :create]

  match '/contact', to: 'contacts#new', via: 'get'

  devise_scope :user do
    get '/signin', to: 'devise/sessions#new'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
    get '/signout', to: 'devise/sessions#destroy'
  end

end

app/models/contact.rb
class Contact
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper
  
  attr_accessor :name, :email, :body, :nickname
  
  validates :name, 
            :presence => true
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ },
	    :presence => true
  
  validates :body,
            :length => { :minimum => 10, :maximum => 1000 }
  
  validates :nickname, 
            :format => { :with => /(?:)/ }
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	default_scope -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
def new
    @contact = Contact.new
end

def create
    @contact = Contact.new(params[:contact])

    if @contact.valid?
      ContactsMailer.contacts_email(@contact).deliver
      redirect_to("/contact", :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :index, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :seasonal)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def sustainability
  end

  def contact
  end

  def products
  end

  def services
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
	    base_title = "George's Seafood"
	    if page_title.empty?
	      base_title
	    else
	      "#{page_title} | #{base_title}"
	    end
	  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/new.html.erb
<% provide(:title, "Contact Us") %>
<%
	keywords %q(contact)
%>
	<div id="susnav"><%= render 'layouts/navbar2' %></div>
<div class="container-fluid" id="contact">
<div class="row">
	<section id="contactbanner">
		
		<div class="container sections">
			<h2 class="sectiontitlepage">Contact Us</h2>
		</div>
	</section>
</div>
<div class="row contactpage">
 <div class="container">
  <div class="row contactrow">
	<div class="col-md-12 col-sm-12 col-xs-12 contactform">
	     
		<%= form_for(@contact) do |f| %>
		    <div class="row formrow">
			<div class="col-md-2 col-sm-2 col-xs-2 formcol">
			    <%= f.label :name %>
			</div>
			<div class="col-md-10 col-sm-6 col-xs-12">
			    <%= f.text_field :name %>
			</div>
		    </div>
		    <div class="row formrow">
			<div class="col-md-2 col-sm-2 col-xs-2 formcol">
			    <%= f.label :email %>
		    	</div>
			<div class="col-md-10 col-sm-6 col-xs-12">
			    <%= f.text_field :email %>
			</div>
		    </div>
		    <div class="row formrow">
			<div class="col-md-2 col-sm-2 col-xs-2 formcol">
			    <%= f.label "Message" %>
			</div>
			<div class="col-md-10 col-sm-6 col-xs-12">
			    <%= f.text_area :body, :rows => 15 %>
			    <div class="hidden"><%= f.text_area :nickname, :hint => 'Leave this field blank!' %></div>
			    <%= f.submit "Submit", :as => :button, class: "btn btn-large btn-sun" %>
			</div>
		    </div>
		<p class="notice"><%= notice %></p>
 	        <p class="alert"><%= alert %></p>
			   

		      	    

		<% end %>
	</div>
  </div>
 </div>
</div>

<div class="row footertact">
  <div class="col-md-6 col-sm-12 col-xs-12" id="footer">
	© 2014 George's Seafood, Inc.
  </div>
</div>
</div>

app/views/contacts/send_mail.html.erb
<h1>Contact#send_mail</h1>
<p>Find me in app/views/contact/send_mail.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="row nav center-block hidden-sm hidden-xs" data-no-turbolink>
     	<div class="col-md-1 col-sm-1 col-xs-1"></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton" id="firstnav">
		<h1>Home</h1>
	</div>'), root_path %></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton">
		<h1>Sustainability</h1>
	</div>'), sustainability_path %></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton">
		<h1>About</h1>
	</div>'), about_path %></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton">
		<h1>Products</h1>
	</div>'), products_path %></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton" id="lastnav">
		<h1>Contact Us</h1>
	</div>'), "/contact" %></div>
	<div class="col-md-1 col-sm-1 col-xs-1"></div>
</div>

<div class="row nav center-block visible-sm visible-xs" data-no-turbolink>
     <div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-6 col-sm-6 col-xs-6 navbutton home">
		HOME
	</div>'), root_path %></div>
     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	<div class="col-sm-6 col-xs-6 dropdown navbutton drop"><span class="box-shadow-menu"></span>
              
		<ul class="dropdown-menu">
		

			<%= link_to (sanitize '<li class="col-md-6 col-sm-12 col-xs-12 navbuttonsmall">
				Products
			</li>'), products_path %>

			<%= link_to (sanitize '<li class="col-md-6 col-sm-12 col-xs-12 navbuttonsmall">
				Sustainability
			</li>'), sustainability_path %>

			<%= link_to (sanitize '<li class="col-md-6 col-sm-12 col-xs-12 navbuttonsmall">
				About
			</li>'), about_path %>

			<%= link_to (sanitize '<li class="col-md-2 col-sm-12 col-xs-12 navbuttonsmall">
				Contact
			</li>'), "/contact" %>
		</ul>
	</div>
      </a>
</div>

app/views/layouts/_navbar2.html.erb
<div class="row nav2 center-block hidden-sm hidden-xs" data-no-turbolink>
     	<div class="col-md-1 col-sm-1 col-xs-1"></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton">
		<h1>Home</h1>
	</div>'), root_path %></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton">
		<h1>Sustainability</h1>
	</div>'), sustainability_path %></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton">
		<h1>About</h1>
	</div>'), about_path %></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton">
		<h1>Products</h1>
	</div>'), products_path %></div>
	<div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-2 col-sm-2 col-xs-2 navbutton">
		<h1>Contact Us</h1>
	</div>'), "/contact" %></div>
	<div class="col-md-1 col-sm-1 col-xs-1"></div>
</div>

<div class="row nav2 center-block visible-sm visible-xs" data-no-turbolink>
     <div data-no-turbolink>
	<%= link_to (sanitize '<div class="col-md-6 col-sm-6 col-xs-6 navbutton">
		HOME
	</div>'), root_path %></div>
     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	<div class="col-sm-6 col-xs-6 dropdown navbutton "><span class="box-shadow-menu"></span>
              
		<ul class="dropdown-menu">
		

			<%= link_to (sanitize '<li class="col-md-6 col-sm-12 col-xs-12 navbuttonsmall">
				Products
			</li>'), products_path %>

			<%= link_to (sanitize '<li class="col-md-6 col-sm-12 col-xs-12 navbuttonsmall">
				Sustainability
			</li>'), sustainability_path %>

			<%= link_to (sanitize '<li class="col-md-6 col-sm-12 col-xs-12 navbuttonsmall">
				About
			</li>'), about_path %>

			<%= link_to (sanitize '<li class="col-md-2 col-sm-12 col-xs-12 navbuttonsmall">
				Contact
			</li>'), "/contact" %>
		</ul>
	</div>
      </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="description" content="The very best seafood distributor on the east coast!" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="keywords" content="<%= yield(:keywords) %>" >
	<meta property="og:image" content="http://littlecreekgermanshepherds.com/assets/seafood.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  	<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
	<link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196">
	<link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
	<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
	<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
	<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
	<meta name="msapplication-TileColor" content="#da532c">
	<meta name="msapplication-TileImage" content="/mstile-144x144.png">
  <script>
	$(document).ready(function(){
		$("body").css({ "visibility": "hidden" });
	});

	$(window).load(function() {
	   $("body").css({ "visibility": "visible" }).hide().fadeIn('slow');

	});
  </script>
</head>
<body>

<div class="container-fluid">

<%= yield %>

</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :seasonal %><br>
    <%= f.check_box :seasonal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% provide(:title, "Products") %>

<%
	keywords %q(seafood, seafood distribution)
%>


	<img class="hidden-xs" id="sill5" src="assets/fish2sill.png">
	<img class="hidden-xs" id="sill9" src="assets/bassill.png">

<div id="susnav"><%= render 'layouts/navbar2' %></div>
<div class="container-fluid" id="productbackground"">
	<div class="row">
		<section id="productpicture">
		
			<div class="container sections">
				<h2 class="sectiontitlepage">Products</h2>
			</div>
		</section>
	</div>
<% if user_signed_in? %>
<div class="container">
	<%= link_to 'New Product', new_product_path, class: "btn btn-lg btn-seafood" %>
	<p class="notice"><%= notice %></p>
 	<p class="alert"><%= alert %></p>
</div>
<% end %>

	<div id="productcontainer">
	 
		<div class="productcategory row">
		 <h2 class="sectionproduct">Seasonal</h2>
			<% if @products.any? %>
				<% @products.each do |product| %>
				 <% if product.seasonal? %>
				  <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 products">
				    <div class="row productrow"><img class="productimage" src='<%= product.image_url(:thumb) %>'></div>
						<h3 style="text-align:center"><%= product.name %></h3>
						<% if user_signed_in? %>
							<div class="row modify">
								<div class="col-md-6 col-sm-6 col-xs-6"><%= link_to 'Edit', edit_product_path(product), class: "btn btn-lg btn-seafood" %></div>
								<div class="col-md-6 col-sm-6 col-xs-6"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-seafood" %></div>
							</div>
						<% end %>
				  </div>
				 <% end %>
				<% end %>
			<% else %>
				<h2 style="text-align:center">We have no seasonal listings at the moment. Please try again later!</h2>
			<% end %>
		 </div>
		 <div class="productcategory row">
		  <h2 class="sectionproduct">Year-round</h2>
				<% if @products.any? %>
				 <% @products.each do |product| %>
				  <% if product.seasonal == false %>
				   <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 products">
				    <div class="row productrow"><img class="productimage" src='<%= product.image_url(:thumb) %>'></div>
						<h3 style="text-align:center"><%= product.name %></h3>
						<% if user_signed_in? %>
							<div class="row modify">
							<div class="col-md-6 col-sm-6 col-xs-6"><%= link_to 'Edit', edit_product_path(product), class: "btn btn-lg btn-seafood" %></div>
							<div class="col-md-6 col-sm-6 col-xs-6"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-seafood" %></div>
							</div>
						<% end %>
				  </div>
				<% end %>
			 <% end %>
			<% else %>
				<h2 style="text-align:center">We have no year-round seafood listings at the moment. Please try again later!</h2>
			<% end %>
		</div>

		<div class="footerduct">
			<div class="col-md-6 col-sm-12 col-xs-12" id="footerduct">
			© 2014 George's Seafood, Inc.
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$(".productimage").each(function() {
			var str = $(this).attr('src');
			var strarray = str.split("/");
			var strid = strarray[4];
			var strpath = (strarray[5].split("thumb_"))[1];
			$(this).wrap($("<a>" ,{
			href: "/uploads/product/image/" + strid + "/" + strpath,
			class: "productlink"
			}));
		});
	$(".productlink").fancybox();
	});
</script>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
<%
keywords %q(about)
%>

<div id="susnav"><%= render 'layouts/navbar2' %></div>
<div class="row">
	<section id="about-top-banner">
		
		<div class="container sections">
			<h2 class="sectionaboutpage">About Us</h2>
		</div>
	</section>
</div>

<div class="row" id="biorow">
	<div class="container" id="biocontainer">
		<div class="biobox">
			<h2 class="header">The Business</h2>		
			<p class="biography">George's Seafood is located in Norfolk, VA; a large military community and the largest naval base in the world. Yet, for George Georgiades, Norfolk was all about the fish. Born and raised here, he took a hobby of sport fishing and turned it into a commercial fishing operation. Norfolk borders the lower Chesapeake Bay and the Atlantic Ocean which provides access to a variety of migrating fish coming and going, domestic USA wild caught fish- George's specialty. Cape Henry and Cape Charles are close by as well, located by the 17 mile Chesapeake Bay Bridge Tunnel, a natural fish haven. </p>
		</div>
		<div class="biobox">
			<h2 class="header">History</h2>
			
			<p class="biography">George started this business 43 years ago; just two years out of high school. During those two years he worked on both commercial and sport fishing boats. George's affiliation with the local commercial and sport fisherman helped build this business. Also, having a father that was a Greek immigrant and local resturant purveyor attributed to his success. But more then anything, was sacrifice and hard work. </p>
			
			<div class="bioimage"><img id="little-george" alt="Young George with his father and a friend"></div>
			<p class="biography" style="padding-top: 2%;">For years George's Seafood was an operation that distributed to local restaurants and supermarkets. As time went on, local fisherman asked George to handle their product, primarily fresh fish. Packing and shipping to mostly the North, ie. Philadelphia, Boston, and New York. In time, business spread South and West- from Georgia and Florida to Illinois, Ohio and Indianapolis.</p>
		</div>
		<div class="biobox">
			<h2 class="header">The Future</h2>
			<p class="biography">The seafood industry has been through a lot of changes and there are more to come. Fortunately, the time invested into customer and vendor relationships over the years has built trust and history that has enabled George's Seafood thrive and survive.  George's dedication and love for this business has allowed him to adapt and succeed in today's challenges for small businesses and the ever-changing seafood industry. </p>
		</div>
			<div class="bioimage"><img id="bass" alt="Two Fisherman, one holding a Bass up proudly"></div>
			<div class="row footertact">
			  <div class="col-md-6 col-sm-12 col-xs-12" id="footer">
				© 2014 George's Seafood, Inc.
			  </div>
			</div>
	</div>

</div>
<script>
	$(document).ready(function() {
		var width = $(window).width();

		if (width > 900) {
			$('#little-george').attr('src', 'assets/Little-George.jpg');
			$('#bass').attr('src', 'assets/BASS.jpg');
		} 
		else {
			$('#little-george').attr('src', 'assets/Little-George-small.jpg');
			$('#bass').attr('src', 'assets/BASS-small.jpg');
		}
	});

</script>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<%
meta keywords: %q(seafood)
%>
<div class="row logo">
		<img id="logo" src="assets/seafood.png">
</div>
<section class="fullimage" id="hero-banner">
	<div class="container sections">
	</div>
</section>
<div class="row nav">
	<%= render 'layouts/navbar' %>
</div>
<section class="fullimagefirst" id="sustainability-banner">
	<div class="container sections">
		<a href="/sustainability"><h2 class="sectiontitle">Sustainable</h2></a>
		<p class="sectiondesc">You can't get more organic than straight from the sea.</p>
	</div>
</section>
<section class="fullimage" id="local-banner">
	<div class="container sections">
		<a href="/about"><h2 class="sectiontitle">Local</h2></a>
		<p class="sectiondesc">Operating from Hampton Roads for 43 years.</p>
	</div>
</section>
<section class="fullimage" id="quality-banner">
	<div class="container sections">
		<a href="/products"><h2 class="sectiontitle">Fresh</h2></a>
		<p class="sectiondesc">Right off the boat.</p>
	</div>
</section>
<section class="fullimage" id="contact-banner">
	<div class="container sections">
		<a href="/contact"><h2 class="sectiontitle">Contact Us</h2></a>
		<p class="sectiondesc">We're listening.</p>
	</div>
</section>
<div class="container">

	<div class="row footer">
		<b>© 2014 George's Seafood, Inc.</b>
	</div>
</div>

<script>
	$(document).ready(function() {
		var logo = document.getElementById('logo');
		var width = $(window).width();

		if (width <= 991 && width > 360){
			$(logo).attr('src', 'assets/seafood-medium.png');
		}

		else if (width <= 360) {
			$(logo).attr('src', 'assets/seafood-small.png');
		}
	});
</script>

app/views/static_pages/sustainability.html.erb
<% provide(:title, "Sustainability") %>

<%
	keywords %q(conservation, regulation)
%>

<script>
$(document).ready(function(){

	$("body").css({ "visibility": "hidden" });
	var ua = navigator.userAgent,
	isMobileWebkit = /WebKit/.test(ua) && /Mobile/.test(ua);
	if (navigator.userAgent.match(/Trident\/7\./) || navigator.userAgent.match(/CrOS/i))
	{
		console.log("IE");
	}
	else if(isMobileWebkit)
	{
		console.log("Mobile");
	}
	else
	{
		console.log("desktop");
		$.stellar( {hideDistantElements: true} );
		$(window).resize(function() {
		   $.stellar('refresh');
		});
	}
});
$(window).load(function(){
	$.stellar('refresh');
});
</script>
	<div class="circle3 hidden-xs" data-stellar-ratio="2"></div>
	<div class="circle4 hidden-xs" data-stellar-ratio="2.5"></div>
	<div class="circle5 hidden-xs" data-stellar-ratio="1.5"></div>
	<div class="circle6 hidden-xs" data-stellar-ratio="1.8"></div>
	<div class="circle7 hidden-xs" data-stellar-ratio="0.6"></div>
	<div class="circle8 hidden-xs" data-stellar-ratio="1.2"></div>
	<div class="circle9 hidden-xs" data-stellar-ratio="1.3"></div>
	<div class="circle10 hidden-xs" data-stellar-ratio="1.6"></div>
	<div class="circle11 hidden-xs" data-stellar-ratio="1.5"></div>
	<div class="circle12 hidden-xs" data-stellar-ratio="1.9"></div>
	<div class="circle13 hidden-xs" data-stellar-ratio="1.8"></div>
	<img class="hidden-xs" id="sill1" data-stellar-ratio="1.1" src="assets/fishsill.png">
	<img class="hidden-xs" id="sill2" data-stellar-ratio="1.1" src="assets/fish2sill.png">
	<img class="hidden-xs" id="sill3" data-stellar-ratio="1.1" src="assets/bassill.png">
<div id="susnav"><%= render 'layouts/navbar2' %></div>
<div class="row ocean">
	<section style="">
		
		<div class="container sections">
			<h2 class="sectiontitlepage">Sustainability</h2>
		</div>
	</section>
	
	<div class="container oceans">
		<div class="circle writing">
			<p>For there to be a future in the seafood industry, there must be fish in the sea to catch. If we catch too many fish, we risk driving species to extinction, and then where would we be? It has happened before, and it can happen again unless we do something about it.
			</p>
		
		</div>
	</div>
</div>
<div class="row ocean2">
	<div class="container oceans">
		<div class="circle2 writing2">
			<p> Regulations help to ensure that the ocean's beauty and biological diversity will still be there for tomorrow to enjoy. In cooperation with NMFS and the VMRC, we strive to provide local seafood directly from fisherman. 
			</p>
		</div>
	</div>
</div>
<div class="row ocean3">
	<div class="container oceans">
		<div id="circle-logos">
				<p id="mi">More Information</p>
				<a href="http://www.nmfs.noaa.gov/"><img id="noaa" src="assets/noaa_logo.png"></a>
				<a href="http://www.mrc.virginia.gov/commercial.shtm"><img src="assets/VMRC_logo.png"></a>
		</div>
	</div>
</div>
<div class="row footersus">
  <div class="col-md-6 col-sm-12 col-xs-12" id="footer">
	© 2014 George's Seafood, Inc.
  </div>
</div>

app/views/users/password/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>